# Generated by Django 5.0.6 on 2024-07-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userPosition',
            field=models.CharField(blank=True, choices=[('프론트엔드', '프론트엔드'), ('backend', '백엔드'), ('fullstack', '풀스택'), ('undefined', '미정')], max_length=20, null=True),
        ),
    ]
