# Generated by Django 5.0.6 on 2024-07-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userPw',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userPwCheck',
        ),
    ]
