# Generated by Django 5.0.6 on 2024-07-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_userposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userPosition',
            field=models.CharField(blank=True, choices=[('frontend', '프론트'), ('backend', '백'), ('fullstack', '풀스택'), ('undefined', '미정')], max_length=20, null=True),
        ),
    ]
