# Generated by Django 5.0.6 on 2024-07-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='input_field',
        ),
    ]
