# Generated by Django 5.0.6 on 2024-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
